name: Run Cloudflare IP SpeedTest

on:
  workflow_dispatch:
  push:

jobs:
  run-ipspeedtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make sure the binary is executable
      run: chmod +x ./ipspeedtest

    - name: Run ipspeedtest with custom parameters
      run: |
        echo "Running ipspeedtest..."
        ./ipspeedtest -file=ip.txt -outfile=ip.csv -port=443 -max=5000 -speedtest=5 -tls=true -url=speed.cloudflare.com/__down?bytes=300000000

    - name: Show generated files
      run: ls -la

    - name: Upload ip.csv File
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: ip-results
        path: ./ip.csv
        if-no-files-found: warn
    - name: Commit and Push Updated ip.csv
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ip.csv
        git commit -m "Update ip.csv from CI" || echo "No changes to commit"
        git push
